default:

install:
	install -d ${TEST_PATH_CASE}/ftp
	install fabfile.py  accel_test_ftp ${TEST_PATH_CASE}/ftp
uninstall:
	rm -f ${TEST_PATH_CASE}/ftp/fabfile.py
	rm -f ${TEST_PATH_CASE}/ftp/accel_test_ftp
clean:
	rm -f *~ \#*
